import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin", "vietnamese"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body className="flex flex-col min-h-screen bg-[#F8FAFC] text-gray-800">
        {/* ================= HEADER ================= */}
        {/* ================= MAIN ================= */}
        <main className="grow w-full">{children}</main>

        {/* ================= FOOTER ================= */}
      </body>
    </html>
  );
}
